allowedOrigins: http://localhost:8080

elkUrl: http://35.222.26.80
elkIndex: index
ffApiKey: 78f5d400-e061-4e96-8300-fc2f0cfc9225
ffMetricKey: errorconfig
ffLogKey: logerrorconfig
target: env

defaultConfig:
  running: true
  name: target
  darkTheme: false
  logConfig:
    logsPerMinute: 60
    errorRate: 3.0
    errorMessage: KnownException
  metricConfig:
    callsPerMinute: 60
    errorRate: 3.0
    minErrorValue: 0.01
    maxErrorValue: 1.00
    shouldDoDelayedCalls: false
    name: target

